repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: check-commit-format
        name: check-commit-format
        entry: python3 ./.git/hooks/pre-commit
        language: system
        types: [commit-msg]