name: RType CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feat/*
      - feat/*/*
  pull_request:
    branches:
      - main

jobs:
  # Build the project
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get cmake version
        run: |
          cmake --version
      
      - name: Set up C++ environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y g++ cmake
          cmake --version
      
      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make
      
      - name: Archive the build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build