name: RType CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build the project
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up C++ environment
        run: |
          apt-get update -y
          apt-get install -y g++ cmake
          mkdir build
          cd build
          cmake ..
          make